
import React, { useState, useEffect } from 'react';
import { Database, Save, AlertCircle, CheckCircle, Terminal } from 'lucide-react';
import { initSupabase, getSavedCredentials } from '../services/supabaseService';

interface Props {
  onConnected: () => void;
}

const SupabaseSetup: React.FC<Props> = ({ onConnected }) => {
  const [url, setUrl] = useState('');
  const [key, setKey] = useState('');
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');

  useEffect(() => {
    const saved = getSavedCredentials();
    if (saved) {
      const success = initSupabase(saved);
      if (success) onConnected();
    }
  }, [onConnected]);

  const handleConnect = () => {
    if (!url || !key) return;
    const success = initSupabase({ url, key });
    if (success) {
      setStatus('success');
      setTimeout(() => onConnected(), 1000);
    } else {
      setStatus('error');
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-100 p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl overflow-hidden">
        <div className="bg-primary-600 p-6 text-white flex items-center gap-3">
          <Database className="w-8 h-8" />
          <h1 className="text-2xl font-bold">إعداد الاتصال بقاعدة البيانات</h1>
        </div>
        
        <div className="p-8">
          <p className="text-slate-600 mb-6 leading-relaxed">
            للبدء، يرجى إدخال بيانات مشروع Supabase الخاص بك. يتم تخزين هذه البيانات محلياً في متصفحك فقط.
          </p>

          <div className="space-y-4 mb-8">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">رابط المشروع (Project URL)</label>
              <input 
                type="text" 
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://xyz.supabase.co"
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:outline-none dir-ltr text-left"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">مفتاح الوصول (Anon Key)</label>
              <input 
                type="password" 
                value={key}
                onChange={(e) => setKey(e.target.value)}
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:outline-none dir-ltr text-left"
              />
            </div>
          </div>

          <button 
            onClick={handleConnect}
            className="w-full bg-primary-600 hover:bg-primary-700 text-white py-3 rounded-lg font-bold flex items-center justify-center gap-2 transition-colors"
          >
            <Save className="w-5 h-5" />
            <span>حفظ واتصال</span>
          </button>

          {status === 'success' && (
            <div className="mt-4 p-4 bg-green-50 text-green-700 rounded-lg flex items-center gap-2">
              <CheckCircle className="w-5 h-5" />
              تم الاتصال بنجاح! جاري التحميل...
            </div>
          )}

          {status === 'error' && (
            <div className="mt-4 p-4 bg-red-50 text-red-700 rounded-lg flex items-center gap-2">
              <AlertCircle className="w-5 h-5" />
              فشل الاتصال. تأكد من صحة البيانات.
            </div>
          )}

          <div className="mt-8 border-t pt-6">
            <h3 className="font-bold text-slate-800 flex items-center gap-2 mb-3">
              <Terminal className="w-5 h-5" />
              تعليمات قاعدة البيانات (SQL)
            </h3>
            <p className="text-sm text-slate-600 mb-2">انسخ الكود التالي وضعه في Supabase SQL Editor لإنشاء الجداول المطلوبة:</p>
            <div className="bg-slate-900 text-slate-50 p-4 rounded-lg text-sm font-mono overflow-x-auto text-left" dir="ltr">
              <pre>{`-- إنشاء جدول الموردين
create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- إنشاء جدول المستخدمين
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- إنشاء جدول العمليات
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  supplier_id bigint references suppliers(id) not null,
  type text not null check (type in ('invoice', 'payment', 'return')),
  amount numeric not null,
  date date not null,
  reference_number text,
  notes text,
  created_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- إنشاء جدول الإعدادات (صف واحد فقط)
create table if not exists app_settings (
  id int primary key default 1 check (id = 1),
  company_name text,
  logo_url text,
  admin_password text
);`}</pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SupabaseSetup;
